config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :shifts
  resources :positions
  resources :locations
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users

  root 'users#index'
end

app/models/position.rb
# frozen_string_literal: true

class Position < ApplicationRecord
  # a Position is a Role, at a particular Location, such as the receptionist as Babington House
  belongs_to :location

  validates :location, :name, presence: true
  validates :min_shift_duration_hrs, :max_shift_duration_hrs, numericality: { greater_than: 0 }

  validate :sane_shift_duration_limits

  private

  def sane_shift_duration_limits
    return unless max_shift_duration_hrs && min_shift_duration_hrs

    if max_shift_duration_hrs < min_shift_duration_hrs
      errors.add(:max_shift_duration_hrs, "can't be less than the minimum")
    end
  end
end

app/controllers/positions_controller.rb
# frozen_string_literal: true

class PositionsController < ApplicationController
  before_action :set_position, only: %i[show edit update destroy]
  before_action :set_locations, only: %i[new create edit update]

  # GET /positions
  # GET /positions.json
  def index
    @positions = Position.all
  end

  # GET /positions/1
  # GET /positions/1.json
  def show; end

  # GET /positions/new
  def new
    @position = Position.new
  end

  # GET /positions/1/edit
  def edit; end

  # POST /positions
  # POST /positions.json
  def create
    @position = Position.new(position_params)

    respond_to do |format|
      if @position.save
        format.html { redirect_to @position, notice: 'Position was successfully created.' }
        format.json { render :show, status: :created, location: @position }
      else
        format.html { render :new }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positions/1
  # PATCH/PUT /positions/1.json
  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to @position, notice: 'Position was successfully updated.' }
        format.json { render :show, status: :ok, location: @position }
      else
        format.html { render :edit }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position.destroy
    respond_to do |format|
      format.html { redirect_to positions_url, notice: 'Position was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_position
    @position = Position.find(params[:id])
  end

  def set_locations
    @locations = Location.all.pluck(:name, :id)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def position_params
    params.require(:position).permit(:location_id, :name, :min_staff, :max_staff, :min_shift_duration_hrs, :max_shift_duration_hrs)
  end
end

app/views/positions/_form.html.erb
<%= form_with(model: position, local: true) do |form| %>
  <% if position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
      <% position.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :location_id, 'Location' %>
    <%= form.select :location_id, @locations %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :min_staff %>
    <%= form.number_field :min_staff %>
  </div>

  <div class="field">
    <%= form.label :max_staff %>
    <%= form.number_field :max_staff %>
  </div>

  <div class="field">
    <%= form.label :min_shift_duration_hrs %>
    <%= form.text_field :min_shift_duration_hrs %>
  </div>

  <div class="field">
    <%= form.label :max_shift_duration_hrs %>
    <%= form.text_field :max_shift_duration_hrs %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/positions/edit.html.erb
<h1>Editing Position</h1>

<%= render 'form', position: @position %>

<%= link_to 'Show', @position %> |
<%= link_to 'Back', positions_path %>

app/views/positions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Positions</h1>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>Name</th>
      <th>Min staff</th>
      <th>Max staff</th>
      <th>Min shift duration hrs</th>
      <th>Max shift duration hrs</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @positions.each do |position| %>
      <tr>
        <td><%= position.location.name %></td>
        <td><%= position.name %></td>
        <td><%= position.min_staff %></td>
        <td><%= position.max_staff %></td>
        <td><%= position.min_shift_duration_hrs %></td>
        <td><%= position.max_shift_duration_hrs %></td>
        <td><%= link_to 'Show', position %></td>
        <td><%= link_to 'Edit', edit_position_path(position) %></td>
        <td><%= link_to 'Destroy', position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Position', new_position_path %>

app/views/positions/new.html.erb
<h1>New Position</h1>

<%= render 'form', position: @position %>

<%= link_to 'Back', positions_path %>

app/views/positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @position.location.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @position.name %>
</p>

<p>
  <strong>Min staff:</strong>
  <%= @position.min_staff %>
</p>

<p>
  <strong>Max staff:</strong>
  <%= @position.max_staff %>
</p>

<p>
  <strong>Min shift duration hrs:</strong>
  <%= @position.min_shift_duration_hrs %>
</p>

<p>
  <strong>Max shift duration hrs:</strong>
  <%= @position.max_shift_duration_hrs %>
</p>

<%= link_to 'Edit', edit_position_path(@position) %> |
<%= link_to 'Back', positions_path %>