config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :shifts
  resources :positions
  resources :locations
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users

  root 'users#index'
end

app/models/shift.rb
# frozen_string_literal: true

class Shift < ApplicationRecord
  # a Shift is a User, working a particular Position for a given period
  MAX_HOURS_PER_WEEK = 40.to_f.freeze
  OPEN_FROM = 7.00
  OPEN_TILL = 3.00
  CLOSING_TIME = ((OPEN_TILL + 0.01)..(OPEN_FROM - 0.01))

  belongs_to :position
  belongs_to :user

  validates :position, :user, :start_at, :end_at, presence: true
  validate :duration_validation
  validate :max_hours_per_week
  validate :max_employees_per_shift
  validate :inside_working_hours

  def duration
    end_at - start_at
  end

  def duration_hours
    duration / 3600
  end

  private

  def duration_validation
    return unless position && end_at && start_at

    if start_at > end_at
      errors.add(:end_at, 'must be after the start of your shift')
      return
    end

    if duration_hours < position.min_shift_duration_hrs
      errors.add(:end_at, "can't be shorter than the minimum shift duration: #{position.min_shift_duration_hrs} hrs")
    end
    if duration_hours > position.max_shift_duration_hrs
      errors.add(:end_at, "can't be longer than the maximum shift duration: #{position.max_shift_duration_hrs} hrs")
    end
  end

  def max_hours_per_week
    return unless user && end_at && start_at

    # assumes we are counting hours in the week they start, otherwise we could compare two weeks accidentally
    shifts_this_week = Shift.where(user_id: user.id).where(
      'start_at > ? AND start_at < ?', start_at.beginning_of_week, start_at.end_of_week
    ).where.not(id: id) # exclude self for updates

    hours_this_week = shifts_this_week.collect(&:duration_hours).sum

    if (duration_hours + hours_this_week) > MAX_HOURS_PER_WEEK
      errors.add(:end_at, "can't be more than the weekly #{MAX_HOURS_PER_WEEK} hour maximum")
    end
  end

  def max_employees_per_shift
    return unless position && end_at && start_at

    overlapping_shifts = Shift.where(
      'end_at > ? AND start_at < ?', start_at, end_at
    ).where.not(id: id).count # exclude self for updates
    if (overlapping_shifts + 1) > position.max_staff
      errors.add(:end_at, "can't overlap shifts. Too many shifts for the given period")
    end
  end

  def inside_working_hours
    return unless start_at && end_at
    return if start_at > end_at # validated elsewhere

    # shift could be 11pm to 3am, need to cover going into next day.
    # or 1am to 3am
    end_time = (end_at.hour.to_f + end_at.min.to_f / 60.0)
    start_time = (start_at.hour.to_f + start_at.min.to_f / 60.0)
    same_day = end_time > start_time

    # this was really complex when I tried to use whitelisted times, using blacklist times is much simpler.
    errors.add(:end_at, "can't be during closing hours") if CLOSING_TIME.include?(end_time)
    errors.add(:start_at, "can't be during closing hours") if CLOSING_TIME.include?(start_time)

    if same_day && (start_time < OPEN_TILL && end_time > OPEN_FROM)
      errors.add(:end_at, "can't be during closing hours")
      errors.add(:start_at, "can't be during closing hours")
    end
  end
end

app/controllers/shifts_controller.rb
# frozen_string_literal: true

class ShiftsController < ApplicationController
  before_action :set_shift, only: %i[show edit update destroy]

  # GET /shifts
  # GET /shifts.json
  def index
    @shifts = Shift.all
  end

  # GET /shifts/1
  # GET /shifts/1.json
  def show; end

  # GET /shifts/new
  def new
    @shift = Shift.new
  end

  # GET /shifts/1/edit
  def edit; end

  # POST /shifts
  # POST /shifts.json
  def create
    @shift = Shift.new(shift_params)

    respond_to do |format|
      if @shift.save
        format.html { redirect_to @shift, notice: 'Shift was successfully created.' }
        format.json { render :show, status: :created, location: @shift }
      else
        format.html { render :new }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shifts/1
  # PATCH/PUT /shifts/1.json
  def update
    respond_to do |format|
      if @shift.update(shift_params)
        format.html { redirect_to @shift, notice: 'Shift was successfully updated.' }
        format.json { render :show, status: :ok, location: @shift }
      else
        format.html { render :edit }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shifts/1
  # DELETE /shifts/1.json
  def destroy
    @shift.destroy
    respond_to do |format|
      format.html { redirect_to shifts_url, notice: 'Shift was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_shift
    @shift = Shift.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def shift_params
    params.require(:shift).permit(:position_id, :user_id, :start_at, :end_at)
  end
end

app/views/shifts/_form.html.erb
<%= form_with(model: shift, local: true) do |form| %>
  <% if shift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shift.errors.count, "error") %> prohibited this shift from being saved:</h2>

      <ul>
      <% shift.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :position_id %>
    <%= form.text_field :position_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :start_at %>
    <%= form.datetime_select :start_at %>
  </div>

  <div class="field">
    <%= form.label :end_at %>
    <%= form.datetime_select :end_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shifts/edit.html.erb
<h1>Editing Shift</h1>

<%= render 'form', shift: @shift %>

<%= link_to 'Show', @shift %> |
<%= link_to 'Back', shifts_path %>

app/views/shifts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shifts</h1>

<table>
  <thead>
    <tr>
      <th>Position</th>
      <th>User</th>
      <th>Start at</th>
      <th>End at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shifts.each do |shift| %>
      <tr>
        <td><%= shift.position.name %></td>
        <td><%= shift.user.name %></td>
        <td><%= shift.start_at %></td>
        <td><%= shift.end_at %></td>
        <td><%= link_to 'Show', shift %></td>
        <td><%= link_to 'Edit', edit_shift_path(shift) %></td>
        <td><%= link_to 'Destroy', shift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shift', new_shift_path %>

app/views/shifts/new.html.erb
<h1>New Shift</h1>

<%= render 'form', shift: @shift %>

<%= link_to 'Back', shifts_path %>

app/views/shifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Position:</strong>
  <%= @shift.position.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @shift.user.name %>
</p>

<p>
  <strong>Start at:</strong>
  <%= @shift.start_at %>
</p>

<p>
  <strong>End at:</strong>
  <%= @shift.end_at %>
</p>

<%= link_to 'Edit', edit_shift_path(@shift) %> |
<%= link_to 'Back', shifts_path %>