config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :shifts
  resources :positions
  resources :locations
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users

  root 'users#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Soho House</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <%= link_to 'Soho House', root_path, class: 'navbar-brand col-sm-3 col-md-2 mr-0', data: { turbolinks: false } %>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">

              <li class="nav-item">
                <%= link_to users_path, class: "nav-link", data: { turbolinks: false } do %>
                  Users
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to locations_path, class: "nav-link", data: { turbolinks: false } do %>
                  Locations
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to positions_path, class: "nav-link", data: { turbolinks: false } do %>
                  Positions
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to shifts_path, class: "nav-link", data: { turbolinks: false } do %>
                  Shifts
                <% end %>
              </li>



            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <%= yield %>
        </main>
      </div>
    </div>



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Icons -->
    <%= javascript_include_tag 'feather.min', 'data-turbolinks-track': 'reload' %>
    <script>
      feather.replace()
    </script>


  </body>
</html>